// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:        "channels",
		Columns:     ChannelsColumns,
		PrimaryKey:  []*schema.Column{ChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chat_id", Type: field.TypeInt, Unique: true},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ChannelSubscribersColumns holds the columns for the "channel_Subscribers" table.
	ChannelSubscribersColumns = []*schema.Column{
		{Name: "channel_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// ChannelSubscribersTable holds the schema information for the "channel_Subscribers" table.
	ChannelSubscribersTable = &schema.Table{
		Name:       "channel_Subscribers",
		Columns:    ChannelSubscribersColumns,
		PrimaryKey: []*schema.Column{ChannelSubscribersColumns[0], ChannelSubscribersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "channel_Subscribers_channel_id",
				Columns:    []*schema.Column{ChannelSubscribersColumns[0]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "channel_Subscribers_user_id",
				Columns:    []*schema.Column{ChannelSubscribersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChannelsTable,
		UsersTable,
		ChannelSubscribersTable,
	}
)

func init() {
	ChannelSubscribersTable.ForeignKeys[0].RefTable = ChannelsTable
	ChannelSubscribersTable.ForeignKeys[1].RefTable = UsersTable
}
