// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChatID holds the string denoting the chatid field in the database.
	FieldChatID = "chat_id"
	// FieldIsAdmin holds the string denoting the isadmin field in the database.
	FieldIsAdmin = "is_admin"
	// EdgeChannels holds the string denoting the channels edge name in mutations.
	EdgeChannels = "Channels"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ChannelsTable is the table the holds the Channels relation/edge. The primary key declared below.
	ChannelsTable = "channel_Subscribers"
	// ChannelsInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelsInverseTable = "channels"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldChatID,
	FieldIsAdmin,
}

var (
	// ChannelsPrimaryKey and ChannelsColumn2 are the table columns denoting the
	// primary key for the Channels relation (M2M).
	ChannelsPrimaryKey = []string{"channel_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsAdmin holds the default value on creation for the "IsAdmin" field.
	DefaultIsAdmin bool
)
